name: inspiriererin
description: A Discord bot that sends you inspirational quotes from InspiroBot
homepage: https://github.com/pixelcmtd/Inspiriererin
version: 0.3.1

environment:
  sdk: ^3.0.0

executables:
  inspiriererin: inspiriererin

dependencies:
  args: ^2.5.0
  http: ^1.0.0
  nyxx: ^6.0.0
  nyxx_extensions: ^4.1.0
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  shelf: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
